# 顶格，没有缩进
llm:
  # 'llm' 下的所有内容，缩进2个空格
  api_type: "openai"
  model: "glm4vfs"
  base_url: "http://192.168.88.7:4000/v1"
  api_key: "sk-1234" # 请确保这里是你的真实有效Key
  max_token: 32000
  temperature: 0.7

# 顶格，没有缩进
rag:
  # 'rag' 下的所有内容，缩进2个空格
  embedding:
    # 'embedding' 下的所有内容，再缩进2个空格
    api_type: "openai"
    model: "bge-m3"
    dimensions: 1024
    api_key: "sk-1234"
    base_url: "http://192.168.88.7:4000/v1"
  retriever:
    top_k: 5

# 顶格，没有缩进
search:
  api_type: 'ddg'
#  api_key: 'YOUR_SEARCH_API_KEY' # 保持注释

# 顶格，没有缩进
human_in_loop: true

# 顶格，没有缩进
project_path: "./workspace"
archive_path: "./archive"