# MetaGPT
# version: 0.8.0
# ...

llm:
  api_type: "openai" # or "azure", "ollama", "gemini", etc.
  model: "glm4vfs" # Default model for general tasks (e.g., gpt-4o, gpt-3.5-turbo)
  base_url: "http://192.168.88.7:4000/v1" # Or your custom base URL for Azure/local models
  api_key: "sk-1234" # <<< IMPORTANT: Replace with your actual OpenAI API key
  max_token: 32000
  temperature: 0.7

# --- Role-specific LLM configurations can be injected at runtime ---
# This section is for components that read directly from config, like RAG.

rag:
  embedding:
    api_type: "openai"
    model: "text-embedding-3-small"
    dimensions: 1536
    api_key: "YOUR_OPENAI_API_KEY" # <<< IMPORTANT: Replace with your actual OpenAI API key
    base_url: "https://api.openai.com/v1"
  retriever:
    # Default retriever config, can be overridden in code
    top_k: 5

search:
  api_type: 'serpapi' # or 'google', 'serper', 'ddg'
  api_key: 'YOUR_SEARCH_API_KEY' # <<< IMPORTANT: Replace with your actual search API key (if using)

# Enable human-in-the-loop for key decisions
human_in_loop: true

# Project-specific settings
project_path: "./workspace"
archive_path: "./archive"