# ~/metagpt/mghier/configs/local_config.yaml

# 角色级别的默认 LLM 资源池
# 当更具体的 role_action_pools 中没有定义时，会使用这里的配置
role_default_pools:
  ChiefPM: 
    - "mistral-medium"  # ChiefPM 默认使用 Mistral Medium，因为它推理强，效率高
  Scheduler:
    - "glm4f"           # Scheduler 使用更经济、快速的 GLM4f
  Executor:
    - "magistral-small" # Executor 的默认模型，适用于一般性写作任务
  Archiver: 
    - "glmz1f"          # Archiver 理论上无需LLM，如果需要，分配一个廉价的快速模型

# Role-Action 级别的特定 LLM 资源池
# 这里的 key 格式是 "RoleClassName-ActionClassName"
# 这具有最高优先级，覆盖 role_default_pools 的配置
role_action_pools:
  # ChiefPM 的 Actions
  ChiefPM-CreateSubOutline:
    - "mistral-large"   # 顶级的推理和长上下文模型
    - "mistral-medium"  # 核心规划，确保高质量
    - "gemini-2.0-flash" 
  
  # Scheduler 的 Actions
  # Scheduler-CreateSubOutline 会被 ChiefPM-CreateSubOutline 覆盖，因为它们可能调用同一个Action
  # 但这里的 Scheduler 的 CreateSubOutline 是指 Scheduler 自己生成子大纲时（如果它有这个行为的话）
  # 实际上，Scheduler更多是调度 ChiefPM 的 CreateSubOutline，所以这个可能用不上
  # 如果 Scheduler 自己需要 LLM 生成子大纲，可以用这个：
  # Scheduler-CreateSubOutline: 
  #   - "magistral-small" 

  Scheduler-CompleteAllTasks: # 这个 Action 通常不需要 LLM，但为完整性保留
    - "glmz1f" # 如果需要LLM，用最快的
    - "mistral-small"      # 次一级但快速的写作模型，用于负载均衡
    - "gemini-2.0-flash" 

  # Executor 的 Actions
  Executor-WriteSection:
    - "glm4f"    # 高质量写作，可以处理复杂内容
    - "mistral-small"      # 次一级但快速的写作模型，用于负载均衡
    - "Qwen3-8B"            # 快速且经济的备用模型
    
  Executor-ReviewSection: # 评审需要高精度和批判性思维
    - "magistral-medium"    # 备用高质量模型
    - "glmz1f" # 如果需要LLM，用最快的
    - "DeepSeek-R1-0528-Qwen3-8B" 

  Executor-ReviseSection: # 修订基于评审意见，也需要高质量
    - "magistral-medium"
    - "mistral-small"
    - "glmz1f" # 如果需要LLM，用最快的

  # Research Action (通常由 ChiefPM 或 Executor 调用)
  # ChiefPM 的 Research Action
  ChiefPM-Research:
    - "gemini-2.0-flash" 
    - "glm4f"                 # 快速备用
    - "magistral-medium"   
  # Executor 的 Research Action (如果 Executor 也要做研究)
  Executor-Research:
    - "gemini-2.0-flash" 
    - "glm4f"
    - "Qwen3-8B"



# MetaGPT 内置的 MCP 服务器绑定
role_mcp_bindings:
  Executor: 
    - "context7" 
  ChiefPM:
    - "context7"

# 层次化文档生成器的特定配置
hierarchical_doc_writer:
  max_depth: 1
  strong_model_semaphore_limit: 3

# 是否启用人工循环
human_in_loop: false

# 项目工作区和归档路径
project_path: "/root/metagpt/mgfr/workspace"
archive_path: "/root/metagpt/mgfr/archive"


# 【新增】指定我们持久化的 DocRAG 引擎的路径
docrag_persist_path: "/root/metagpt/ragdata/ragdata"

# 【新增】经验池配置 - 用于知识沉淀
exp_pool:
  enabled: true
  enable_read: true
  enable_write: true
  persist_path: .mghier_exp_pool
  retrieval_type: bm25
  use_llm_ranker: true

# 【新增】Research Action 配置
research:
  # 提示词模板配置
  prompt_templates:
    # 系统提示词 - 基础版本
    base_system_prompt: |
      You are an expert research assistant using a ReAct (Reasoning + Action) framework.
      Your goal is to systematically gather and analyze information to answer the user's question.
      
      # Available Tools:
      {available_tools}
      
      # Important Rules:
      1. ONLY use tools listed above. Do NOT invent or assume tools exist.
      2. Use JSON format for ALL responses.
      3. When analyzing documentation, use the FINISH tool with your analysis result.
      4. Be concise and focused on the original question.
      
      # Original Goal:
      {original_goal}
    
    # 工具指令模板
    tool_instruction_template: |
      **Available Tools:**
      {available_tools}
      
      **Important Notes for Tool Usage:**
      - When using the 'resolve-library-id' tool, you MUST provide the 'libraryName' argument.
      - When using the 'get-library-docs' tool, you MUST provide the 'context7CompatibleLibraryID' argument.
      - When you have gathered sufficient information, use the FINISH tool with your analysis result.
      - DO NOT use tools like 'parse-documentation', 'MANUAL_ANALYSIS', or 'ANALYZE' - they don't exist.
    
    # 完成指令模板
    completion_instruction: |
      Based on the information gathered, provide a comprehensive answer to the original question.
      Structure your response clearly and cite specific information from the documentation when relevant.
  
  # 工具重试配置
  retry_config:
    max_retry_attempts: 3
    retry_models: 
      - "gemini-2.0-flash"
      - "glm4f"
      - "magistral-medium"
      - "Qwen3-8B"
  
  # JSON解析配置
  json_parsing:
    # 最大重试次数
    max_retry_attempts: 3
    # 是否启用严格的JSON验证
    strict_validation: true
    # 备用解析策略
    fallback_strategies:
      - code_parser
      - regex_extraction
      - manual_clean
    
  # 工具验证配置
  tool_validation:
    # 是否启用工具验证
    enabled: true
    # 是否在工具不存在时提供替代方案
    provide_alternatives: true
    # 允许的工具列表（如果为空，则使用MCP服务器返回的工具）
    allowed_tools: []
  
  # 内置分析工具配置
  builtin_tools:
    # 是否启用内置文档分析
    enable_document_analysis: true
    # 文档分析提示词
    document_analysis_prompt: |
      Analyze the following documentation content and extract key information about roles and actions.
      
      Documentation content:
      {documentation_content}
      
      Focus on:
      1. What are the main roles in this system?
      2. What are the key actions or functions?
      3. How do roles and actions interact?
      
      Provide a structured analysis with specific examples from the documentation.